### PR TITLE
Link Code of Conduct

### PR DESCRIPTION
**Pull request by terrajobst**
See [this policy rule](https://github.com/dotnet/org-policy/blob/master/doc/PR15.md) for more details.

### CODE REVIEW

**Comment by terrajobst** [comment]
@jonathanpeppers

**Comment by jonathanpeppers** [comment]
@akoeplinger can you merge? doesn't look like I have access

**Comment by akoeplinger** [comment]
This is a fork of ikvm and I think the guidance was to not add the CoC to such repos. @terrajobst ok to close?

**Comment by terrajobst** [comment]
Totally. I submitted it anyway because I'm the domain expert to know what's a fork and what isn't.

**Pull request closed without merging**
